### ISSUE TITLE
v2 port?

### ISSUE THREAD

**Issue by terrytheplatypus** [gosub/forsitan-modulare#1]
do you have any plans to do the v2 port? i like using pavo so i could submit a pull request or do a fork if you haven't gotten around to that.

**Comment by gosub** [comment]
Hi, I still haven't found the time to try to port my modules to 2.0 :disappointed:
My aging pc is also having problems running vcv 2, so it's even more difficult. If you want to submit a pull request, I'll try to compile it and publish. I should also see if someone published an updated github action to compile 2.0 modules for all the platforms.

Anyway, thanks and happy holidays!

**Comment by gosub** [comment]
@terrytheplatypus I've been able to push a preliminary beta build for v2, there is a downloadable release v2.0.0

**Comment by gosub** [comment]
I've completed the port to v2 and submitted the request to be included in the Library
https://github.com/VCVRack/library/issues/681#issuecomment-1368448965
